
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Project, Client } from '../types';
import { formatCurrency } from '../utils';

export const generateProjectInvoice = (project: Project, client: Client | undefined, metadata: any) => {
    const doc = new jsPDF();
    const currency = project.currency || 'AUD';

    // --- Data Extraction ---
    const billedBy = metadata.billedBy;
    const billedTo = metadata.billedTo;
    const invoiceNumber = metadata.invoiceNumber;
    const dueDate = metadata.dueDate ? new Date(metadata.dueDate).toLocaleDateString('en-GB') : 'Upon Completion';
    const invoiceDate = new Date().toLocaleDateString('en-GB');
    const footerText = "Novalink Innovations (Pvt) Ltd | PV 00337332 | info@novalinkinnovations.com | www.novalinkinnovations.com";

    // --- Calculations from Metadata (Respecting Toggles) ---
    const activeItems = (metadata.items || []).filter((i: any) => i.included);
    const totalAmount = activeItems.reduce((sum: number, i: any) => sum + i.amount, 0);

    // --- Header Section ---
    try {
        doc.addImage('/logo.png', 'PNG', 14, 15, 60, 15);
    } catch (e) {
        doc.setFillColor(10, 105, 225);
        doc.roundedRect(14, 15, 12, 12, 3, 3, 'F');
        doc.setFont("helvetica", "bold"); doc.setFontSize(22); doc.setTextColor(15, 23, 42);
        doc.text("Novalink", 28, 24);
    }



    // Billed By (Left)
    doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(15, 23, 42);
    doc.text("BILLED BY", 14, 45);
    doc.setFont("helvetica", "normal"); doc.setTextColor(71, 85, 105);
    doc.text(billedBy.name, 14, 50);
    // Split address by comma if it's a long string
    const addrLines = billedBy.address.split(', ');
    addrLines.forEach((line: string, i: number) => doc.text(line, 14, 55 + (i * 5)));
    doc.text(`Email: ${billedBy.email}`, 14, 70);
    doc.text(`Phone: ${billedBy.phone}`, 14, 75);

    // Billed To (Right)
    const rightColumnX = 120;
    doc.setFont("helvetica", "bold"); doc.text("BILLED TO", rightColumnX, 45);
    doc.setFont("helvetica", "normal"); doc.setTextColor(71, 85, 105);
    doc.text(billedTo.company, rightColumnX, 50);
    doc.text(billedTo.name, rightColumnX, 55);
    doc.text(billedTo.email, rightColumnX, 60);
    doc.text(billedTo.phone, rightColumnX, 65);
    if (billedTo.address) doc.text(billedTo.address, rightColumnX, 70);

    // Invoice Details Box
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, 85, 182, 25, 4, 4, 'F');

    doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(100, 116, 139);
    doc.text("INVOICE NUMBER", 20, 93);
    doc.text("DATE OF ISSUE", 70, 93);
    doc.text("DUE DATE", 120, 93);
    doc.text("SETTLEMENT STATUS", 160, 93, { align: 'right' });

    doc.setTextColor(15, 23, 42); doc.setFontSize(11);
    doc.text(invoiceNumber, 20, 101);
    doc.text(invoiceDate, 70, 101);
    doc.text(dueDate, 120, 101);
    doc.text("UNPAID", 186, 101, { align: 'right' });

    // --- Body Section (Table) ---
    const tableData = activeItems.map((item: any) => [
        item.type,
        item.description,
        formatCurrency(item.amount, currency)
    ]);

    autoTable(doc, {
        startY: 120,
        head: [['SERVICE CATEGORY', 'DEPLOYMENT DESCRIPTION', 'AMOUNT']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255], fontSize: 9, fontStyle: 'bold', cellPadding: 5 },
        bodyStyles: { fontSize: 10, textColor: [71, 85, 105], cellPadding: 5 },
        columnStyles: { 2: { halign: 'right', fontStyle: 'bold', textColor: [15, 23, 42] } },
        margin: { left: 14, right: 14 }
    });

    // --- Summary Section ---
    const finalY = (doc as any).lastAutoTable.finalY + 15;
    doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.setTextColor(15, 23, 42);
    doc.text("NET SETTLEMENT AMOUNT:", 110, finalY);
    doc.setFontSize(14); doc.setTextColor(37, 99, 235);
    doc.text(formatCurrency(totalAmount, currency), 186, finalY, { align: 'right' });

    // Payment Logic Summary
    doc.setFillColor(239, 246, 255);
    doc.roundedRect(14, finalY + 10, 182, 12, 2, 2, 'F');
    doc.setFontSize(9); doc.setTextColor(37, 99, 235);
    doc.text(`This invoice reflects the current outstanding balance logic for project ${project.name}.`, 105, finalY + 18, { align: 'center' });

    // --- Footer ---
    const pageHeight = doc.internal.pageSize.height;
    doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(148, 163, 184);
    doc.text(footerText, 105, pageHeight - 15, { align: 'center' });
    doc.text("Generated by NovaLink Intelligence Platform | Protocol v2.1", 105, pageHeight - 10, { align: 'center' });

    doc.save(`${invoiceNumber}_${project.name.replace(/\s+/g, '_')}.pdf`);
};

